spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paybox
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      dialect: org.hibernate.dialect.MySqQL5Dialect
server:
  port: 8080
  address: 0.0.0.0